# This file extracts the top 10 configs from the log file based on wins and then average CCPFA time, and ranks them. It is meant to be run on the log file generated by compare_algos.py, which contains the analysis of all configurations.

import re
from collections import defaultdict
import argparse

parser = argparse.ArgumentParser(description="Extract top 10 configs from log file")
parser.add_argument("log_file", help="Path to the log file")

args = parser.parse_args()

# get top 10 configs by wins (CCPFA better than both CPFA and GCFA) and then by average CCPFA time
with open(args.log_file) as f:
    content = f.read()

blocks = re.split(r'Analyzing ', content)

wins = defaultdict(int)
total = defaultdict(int)

for block in blocks:
    if not block.strip():
        continue
    lines = block.strip().split('\n')
    header = lines[0].strip()
    m_header = re.match(r'(resource_collection_all/resource_collection_analysis_[^/]+)/(\w+_distribution)', header)
    if not m_header:
        continue
    config_base = m_header.group(1)

    for line in lines[1:]:
        m = re.match(r'\s*\d+\s+(\d+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)', line)
        if m:
            cpfa = float(m.group(2))
            gcfa = float(m.group(3))
            ccpfa = float(m.group(4))
            total[config_base] += 1
            if ccpfa < cpfa and ccpfa < gcfa:
                wins[config_base] += 1

results = [(wins[k], total[k], k) for k in total]
results.sort(reverse=True)

print(f'{"Wins":>5}  {"Total":>6}  Config')

for w, t, cfg in results[:20]:
    short = cfg.replace('resource_collection_all/resource_collection_analysis_', '')
    print(f'{w:>5}  {t:>6}  {short}')

# use top 10 configs by wins to extract average CCPFA times and min/max for those configs
with open(args.log_file) as f:
    content = f.read()

blocks = re.split(r'Analyzing ', content)

perfect = [
    cfg for _, _, cfg in results[:10]
]

cfg_values = defaultdict(list)
for block in blocks:
    if not block.strip():
        continue
    lines = block.strip().split('\n')
    header = lines[0].strip()
    matched = next((c for c in perfect if header.startswith(c)), None)
    if not matched:
        continue
    for line in lines[1:]:
        m = re.match(r'\s*\d+\s+(\d+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)', line)
        if m:
            cfg_values[matched].append(float(m.group(4)))

results = []
for cfg, vals in cfg_values.items():
    avg = sum(vals)/len(vals)
    results.append((avg, cfg, vals))

results.sort()
print(f'{"Rank":>4}  {"Avg CCPFA":>10}  {"Min":>8}  {"Max":>8}  Config')
for rank, (avg, cfg, vals) in enumerate(results, 1):
    short = cfg.replace('resource_collection_all/resource_collection_analysis_', '')
    print(f'{rank:>4}  {avg:>10.3f}  {min(vals):>8.3f}  {max(vals):>8.3f}  {short}')

from PIL import Image, ImageDraw, ImageFont
import os

BASE = 'analysis_plots_resource_collection_all'

configs_ranked = [
    (perfect[0].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[0].replace('resource_collection_all/', '')),
    (perfect[1].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[1].replace('resource_collection_all/', '')),
    (perfect[2].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[2].replace('resource_collection_all/', '')),
    (perfect[3].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[3].replace('resource_collection_all/', '')),
    (perfect[4].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[4].replace('resource_collection_all/', '')),
    (perfect[5].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[5].replace('resource_collection_all/', '')),
    (perfect[6].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[6].replace('resource_collection_all/', '')),
    (perfect[7].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[7].replace('resource_collection_all/', '')),
    (perfect[8].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[8].replace('resource_collection_all/', '')),
    (perfect[9].replace('resource_collection_all/resource_collection_analysis_', ''), perfect[9].replace('resource_collection_all/', ''))
]

distributions = ['cluster', 'powerlaw', 'random']
dist_labels = ['Cluster', 'Powerlaw', 'Random']

# Load all images and get uniform cell size
imgs = []
for label, dirname in configs_ranked:
    row = []
    for dist in distributions:
        path = os.path.join(BASE, dirname, f'{dist}_resource_analysis_plot.png')
        img = Image.open(path)
        row.append(img)
    imgs.append(row)

# Target cell size
cell_w, cell_h = 600, 400
label_col_w = 280
header_h = 40
row_label_h = 20

n_rows = len(configs_ranked)
n_cols = len(distributions)

total_w = label_col_w + n_cols * cell_w
total_h = header_h + n_rows * (cell_h + row_label_h)

canvas = Image.new('RGB', (total_w, total_h), (255, 255, 255))
draw = ImageDraw.Draw(canvas)

try:
    font_header = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 18)
    font_label  = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', 13)
    font_rank   = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 13)
except:
    font_header = font_label = font_rank = ImageFont.load_default()

# Column headers
for ci, dlabel in enumerate(dist_labels):
    x = label_col_w + ci * cell_w + cell_w // 2
    draw.text((x, header_h // 2), dlabel, fill=(0,0,0), font=font_header, anchor='mm')

# Rows
for ri, ((short_label, dirname), row_imgs) in enumerate(zip(configs_ranked, imgs)):
    y_top = header_h + ri * (cell_h + row_label_h)

    # Row label on left
    rank_str = f'#{ri+1}'
    draw.text((10, y_top + cell_h // 2 - 10), rank_str, fill=(180,0,0), font=font_rank)
    # wrap label
    draw.text((45, y_top + cell_h // 2 - 10), short_label, fill=(0,0,0), font=font_label)

    for ci, img in enumerate(row_imgs):
        img_resized = img.resize((cell_w, cell_h), Image.LANCZOS)
        x = label_col_w + ci * cell_w
        canvas.paste(img_resized, (x, y_top))

    # thin separator line
    draw.line([(0, y_top + cell_h + row_label_h - 1), (total_w, y_top + cell_h + row_label_h - 1)], fill=(200,200,200))

out_path = f'top10_ccpfa_configs_review_{args.log_file.split("/")[-1].split(".")[0]}.png'
canvas.save(out_path, dpi=(150, 150))
print(f'Saved: {out_path}  ({total_w}x{total_h}px)')